# Generated by Django 4.2.6 on 2023-10-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
