# Generated by Django 4.2.6 on 2023-10-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lecturer"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedback.feedback"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lecturer"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("student", "feedback")},
        ),
    ]
